<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MaintenancesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('maintenances')->delete();

        \DB::table('maintenances')->insert(array (
            0 =>
            array (
                'id' => 1,
                'gmao_id' => NULL,
                'material_id' => 46,
            'description' => 'Démonté la presse (Franck et Alexis), changé les barreaux (OLEXA), puis remonté la presse (Franck, Emeric).',
                'reason' => 'Problème d\'écrou de serrage des profils de vis.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'both',
                'started_at' => '2023-06-08 22:02:34',
                'finished_at' => '2023-06-15 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-06-08 22:02:34',
                'updated_at' => '2023-06-15 22:02:34',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'gmao_id' => NULL,
                'material_id' => 118,
                'description' => 'Changé 5 ventouses.',
                'reason' => 'Problème de prise de sac dans le magasin.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'internal',
                'started_at' => '2023-06-14 22:02:34',
                'finished_at' => '2023-06-14 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-06-14 22:02:34',
                'updated_at' => '2023-06-14 22:02:34',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'gmao_id' => NULL,
                'material_id' => 75,
                'description' => 'Réparation de la pédale du pre-conditionneur.',
                'reason' => 'Pédale pre-con HS.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'external',
                'started_at' => '2023-06-16 22:02:34',
                'finished_at' => '2023-06-16 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-06-16 22:02:34',
                'updated_at' => '2023-06-16 22:02:34',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'gmao_id' => NULL,
                'material_id' => 133,
                'description' => 'Révision mensuel de la CTA et enlevé le défaut présent.',
                'reason' => 'Révision mensuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'external',
                'started_at' => '2023-06-23 22:02:34',
                'finished_at' => '2023-06-23 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-06-23 22:02:34',
                'updated_at' => '2023-06-23 22:02:34',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'gmao_id' => NULL,
                'material_id' => 82,
                'description' => 'Démonté et changé le flexible.',
                'reason' => 'Flexible de vidange du réservoir percé.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'internal',
                'started_at' => '2023-06-23 22:02:34',
                'finished_at' => '2023-06-23 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-06-23 22:02:34',
                'updated_at' => '2023-06-23 22:02:34',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'gmao_id' => NULL,
                'material_id' => 134,
                'description' => 'Démonté et changer les joints des robinets des chaudières 1 et 3.',
                'reason' => 'Fuite sur les contrôles de niveau d\'eau des chaudières 1 et 3.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'external',
                'started_at' => '2023-07-06 22:02:34',
                'finished_at' => '2023-07-06 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-07-06 22:02:34',
                'updated_at' => '2023-07-06 22:02:34',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'gmao_id' => NULL,
                'material_id' => 135,
                'description' => 'Démonté et changer les joints pour réparer la fuite d\'eau.',
                'reason' => 'Fuite d\'eau sous le karcher eau chaude.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'external',
                'started_at' => '2023-07-18 22:02:34',
                'finished_at' => '2023-07-18 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-07-18 22:02:34',
                'updated_at' => '2023-07-18 22:02:34',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'gmao_id' => NULL,
                'material_id' => 133,
                'description' => 'Révision mensuel de la CTA.',
                'reason' => 'Révision mensuel.',
                'user_id' => 3,
                'type' => 'preventive',
                'realization' => 'external',
                'started_at' => '2023-07-25 22:02:34',
                'finished_at' => '2023-07-25 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-07-25 22:02:34',
                'updated_at' => '2023-07-25 22:02:34',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'gmao_id' => NULL,
                'material_id' => 56,
                'description' => 'Démonté, nettoyé au Karcher et eau chaude l\'ensemble de la tuyauterie puis remonté.',
                'reason' => 'Bourrage de la tuyauterie de la PPH1.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'internal',
                'started_at' => '2023-07-26 22:02:34',
                'finished_at' => '2023-07-31 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-07-26 22:02:34',
                'updated_at' => '2023-07-31 22:02:34',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'gmao_id' => NULL,
                'material_id' => 135,
                'description' => 'Emmené en réparation chez Fitech.',
                'reason' => 'Fuite d\'eau sur le tuyau du Karcher station de lavage.',
                'user_id' => 1,
                'type' => 'curative',
                'realization' => 'external',
                'started_at' => '2023-07-22 22:02:34',
                'finished_at' => '2023-07-28 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-07-22 22:02:34',
                'updated_at' => '2023-07-28 22:02:34',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'gmao_id' => NULL,
                'material_id' => 42,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'gmao_id' => NULL,
                'material_id' => 43,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'gmao_id' => NULL,
                'material_id' => 44,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'gmao_id' => NULL,
                'material_id' => 45,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'gmao_id' => NULL,
                'material_id' => 46,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'gmao_id' => NULL,
                'material_id' => 47,
                'description' => 'Vidangé l\'huile du motoréducteur de la Presse.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-02 22:02:34',
                'finished_at' => '2023-08-02 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-02 22:02:34',
                'updated_at' => '2023-08-02 22:02:34',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'gmao_id' => NULL,
                'material_id' => 16,
                'description' => 'Vidangé l\'huile du motoréducteur du conditionneur.',
                'reason' => 'Renouvellement de l\'huile du motoréducteur annuel.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-03 22:02:34',
                'finished_at' => '2023-08-03 22:02:34',
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-03 22:02:34',
                'updated_at' => '2023-08-03 22:02:34',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'gmao_id' => NULL,
                'material_id' => 68,
                'description' => 'Ouvert et vérifié l\'intégrité des grilles.',
                'reason' => 'Vérification annuel des 2 grilles du broyeur.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'internal',
                'started_at' => '2023-08-08 22:02:00',
                'finished_at' => '2023-08-08 22:02:00',
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-08 22:02:34',
                'updated_at' => '2023-08-11 23:24:40',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'gmao_id' => NULL,
                'material_id' => 12,
            'description' => 'Ouvert le Broyeur (Emeric), changé la grille et certaines pièces du broyeur puis remonté (Emeric & Bourgogne du Sud Maintenance)',
                'reason' => 'Vérification annuel de la grille du broyeur.',
                'user_id' => 1,
                'type' => 'preventive',
                'realization' => 'both',
                'started_at' => '2023-08-08 08:09:00',
                'finished_at' => NULL,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-14 08:10:53',
                'updated_at' => '2023-08-14 08:11:54',
                'deleted_at' => NULL,
            ),
        ));


    }
}
