<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MaterialsTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();

        $materials = [
            [
                'user_id' => 1,
                'name' => 'BMP1',
                'description' => 'Boisseau de farine extérieur n°1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BMP2',
                'description' => 'Boisseau de farine extérieur n°2.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VMP1',
                'description' => 'Vis matière première sous boisseau BMP1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VMP2',
                'description' => 'Vis matière première sous boisseau BMP2.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ELP1',
                'description' => 'Élévateur à palle avant EMT1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'EMT1',
                'description' => 'Émietteur servant à casser la graine de soja.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ASPNS1',
                'description' => 'Aspiration du nettoyeur/séparateur de graines servant' .
                ' à aspirer les coques séparées de la graine.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'NS1B1',
                'description' => 'Vibrant n°1 du nettoyeur/séparateur servant à faire vibrer les grilles.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'NS1B2',
                'description' => 'Vibrant n°2 du nettoyeur/séparateur servant à faire vibrer les grilles.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'NS1V',
                'description' => 'Vis du nettoyeur/séparateur servant à faire évacuer les coques aspirées.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL1',
                'description' => 'Écluse servant pour l\'aspiration du NS1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BRC',
                'description' => 'Broyeur à coques servant à broyer les coques et les' .
                ' souffler dans le boisseau à coque BC1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BC1',
                'description' => 'Boisseau à coque servant à stocker les coques broyées.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'SO1',
                'description' => 'Souffleur servant à souffler la graine broyeur dans le conditionneur.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL2',
                'description' => 'Écluse servant pour le souffleur n°1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CV1',
                'description' => 'Conditionneur servant à chauffer la graine de soja.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'EXT1',
                'description' => 'Extracteur d\'air servant à ventiler les plateaux du conditionneur.',
                'zone_id' => 1,
                'incident_count' => 1,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'PV1',
                'description' => 'Panoplie vapeur du conditionneur.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VM1',
                'description' => 'Vis sous conditionneur servant à transporter la graine chaude.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'EL2',
                'description' => 'Élévateur à godet servant à alimenter le transporteur à chaîne TCM1.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'TCM1',
                'description' => 'Transporteur à chaîne servant à distribuer les presses.',
                'zone_id' => 1,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T1TCM1',
                'description' => 'Trappe à air comprimé n°1 servant à remplir la trémie de la presse 1.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T2TCM1',
                'description' => 'Trappe à air comprimé n°2 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T3TCM1',
                'description' => 'Trappe à air comprimé n°3 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T4TCM1',
                'description' => 'Trappe à air comprimé n°4 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T5TCM1',
                'description' => 'Trappe à air comprimé n°5 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T6TCM1',
                'description' => 'Trappe à air comprimé n°6 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T7TCM1',
                'description' => 'Trappe à air comprimé n°7 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T8TCM1',
                'description' => 'Trappe à air comprimé n°8 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T9TCM1',
                'description' => 'Trappe à air comprimé n°9 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'T10TCM1',
                'description' => 'Trappe à air comprimé n°10 servant à remplir la trémie de la presse 2.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD1',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD2',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD3',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD4',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD5',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD6',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD7',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD8',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD9',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VD10',
                'description' => 'Vis distributrice servant à alimenter la presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P1',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 1,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P2',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P3',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P4',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P5',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 1,
                'maintenance_count' => 2,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P6',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P7',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P8',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P9',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'P10',
                'description' => 'Presse.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CHY1',
                'description' => 'Groupe hydraulique servant pour les nez de presse 1 à 7.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CHY2',
                'description' => 'Groupe hydraulique servant pour les nez de presse 8 à 10.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VH1',
                'description' => 'Vis d\'huile servant à transporter l\'huile des presse 1 à 7 à la pompe.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VH2',
                'description' => 'Vis d\'huile servant à transporter l\'huile des presse 8 à 10 à la pompe.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'PPH1',
                'description' => 'Pompe à huile servant à emmener l\'huile dans la cuve.',
                'zone_id' => 2,
                'incident_count' => 2,
                'maintenance_count' => 1,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'AGT1',
                'description' => 'Agitateur servant à homogénéiser l\'huile dans la cuve.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CHH',
                'description' => 'Cuve d\'huile.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'FP1',
                'description' => 'Filtres plateaux horizontaux servant à filtrer l\'huile.',
                'zone_id' => 2,
                'incident_count' => 1,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'DEB1',
                'description' => 'Débitmètre servant à mesurer la quantité d\'huile filtrée.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'TCI1',
                'description' => 'Transporteur à chaîne incliné servant à transporter le tourteaux dans le concasseur.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'C1',
                'description' => 'Concasseur servant à concasser les tourteaux en petits morceaux.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL4',
                'description' => 'Écluse servant pour le concasseur.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'REF1',
                'description' => 'Ventilateur du refroidisseur servant à refroidir les tourteaux.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'EV REF1',
                'description' => 'Trappe à air comprimé servant à vidanger le refroidisseur.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL3',
                'description' => 'Écluse servant pour le refroidisseur.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VT1',
                'description' => 'Vis servant à transporter le tourteaux au broyeur.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BRT1',
                'description' => 'Broyeur à marteaux servant à broyer le tourteaux en farine.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ELP3',
                'description' => 'Élévateur à palle servant à monter la farine dans le boisseau.',
                'zone_id' => 2,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BTF1',
                'description' => 'Boisseau de farine de soja.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'FV1',
                'description' => 'Fond vibrant du boisseau BTF1',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VF1',
                'description' => 'Vis servant à transporter la farine dans le doseur de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P31 Doseur',
                'description' => 'Doseur de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 1,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P32 By-pass Pré-conditionneur',
                'description' => 'By-pass du pré-conditionneur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P33 Pré-conditionneur',
                'description' => 'Pré-conditionneur.',
                'zone_id' => 3,
                'incident_count' => 1,
                'maintenance_count' => 1,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Accessoires Pré-conditionneur/Extrudeur',
                'description' => 'Les accessoires du pré-conditionneur et de l\'extrudeur (colliers, manches etc).',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P34 Panoplie Vapeur',
                'description' => 'Panoplie Vapeur du pré-conditionneur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P35 Pompe Eau Pré-conditionneur',
                'description' => 'Pompe à eau du pré-conditionneur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P36 Pompe Eau Extrudeur',
                'description' => 'Pompe à eau de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT Moteur vis',
                'description' => 'Moteur/vis de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT Fourreaux',
                'description' => 'Fourreaux de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT Groupe Froid',
                'description' => 'CXT Groupe Froid de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 1,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT Filière',
                'description' => 'Filières de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P38 Couteau',
                'description' => 'Couteau de l\'extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P39 Convoyeur Pneumatique',
                'description' => 'Convoyeur pneumatique sortie extrudeur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P40 By-pass vibrant',
                'description' => 'By-pass entrée sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT P41 Tapis Vibrant',
                'description' => 'Tapis vibrant entrée sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M11 Tapis',
                'description' => 'Tapis du sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT Z1 Chauffage',
                'description' => 'Chauffage du sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M31 Ventilateur',
                'description' => 'Ventilateur du sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M32 Ventilateur',
                'description' => 'Ventilateur du sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M41 Extracteur d\'Air',
                'description' => 'Extracteur d\'air du sécheur.',
                'zone_id' => 3,
                'incident_count' => 1,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M51 Convoyeur',
                'description' => 'Convoyeur sortie sécheur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M52 Élévateur',
                'description' => 'Élévateur sortie sécheur servant à emmener le produit dans le refroidisseur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M53A Convoyeur Refroidisseur',
                'description' => 'Convoyeur servant à transporter le produit à l\'intérieur du refroidisseur.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M53B Ventilateur Refroidisseur',
                'description' => 'Ventilateur servant à refroidir le produit.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CXT M53C Ventilateur Refroidisseur',
                'description' => 'Ventilateur servant à refroidir le produit.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'SO2',
                'description' => 'Souffleur servant à emmener le produit sortie refroidisseur vers boisseaux.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BD2',
                'description' => 'Boite directionnelle servant à orienter le produit' .
                ' vers les boisseaux ou la station de remplissage Big-Bag.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BD1',
                'description' => 'Boite directionnelle servant à orienter le produit' .
                ' vers le boisseau BTF1 ou BTF2.',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Évier/Plan de Travail',
                'description' => 'Évier et plan de travail situé en salle blanche',
                'zone_id' => 3,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Trémie Tampon',
                'description' => 'Trémie tampon du recyclage des fines.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'M1A',
                'description' => 'Vis de vidange de la trémie tampon.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'M1B',
                'description' => 'Dévouteur de la trémie tampon.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'M1C',
                'description' => 'Vis de transfert entre les 2 trémies.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Trémie Doseuse',
                'description' => 'Trémie doseuse du recyclage des fines.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 1,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'M2A',
                'description' => 'Vis doseuse de la trémie doseuse.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'M2B',
                'description' => 'Dévouteur de la trémie doseuse.',
                'zone_id' => 4,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BPF1',
                'description' => 'Boisseau de produit fini 1.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'BPF2',
                'description' => 'Boisseau de produit fini 2.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'FV2',
                'description' => 'Fond vibrant du boisseau BPF1.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'FV3',
                'description' => 'Fond vibrant du boisseau BPF2.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VPF1',
                'description' => 'Vis vidange du boisseau BPF1.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VPF2',
                'description' => 'Vis vidange du boisseau BPF2.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Trémie sous Boisseaux BPF1/BPF2',
                'description' => 'La trémie sous les boisseaux BPF1 et BPF2.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 1,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'SO3',
                'description' => 'Souffleur servant à pousser le produit dans la trémie de l\'ensacheuse.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL5',
                'description' => 'Écluse servant pour le souffleur SO3.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Ensacheuse',
                'description' => 'Ensacheuse pondérale pour le remplissage des sacs de PVT.',
                'zone_id' => 5,
                'incident_count' => 2,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 1,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Tricoteuse',
                'description' => 'Tricoteuse de l\'ensacheuse.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Détecteur aimant Ensacheuse',
                'description' => 'Détecteur aimant de l\'ensacheuse.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Étiqueteuse Ensacheuse',
                'description' => 'Détecteur aimant de l\'ensacheuse.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Palettiseur',
                'description' => 'Palettiseur.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Filmeuse',
                'description' => 'Filmeuse.',
                'zone_id' => 5,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'DOS1',
                'description' => 'Doseur de la station de vidange BB.',
                'zone_id' => 6,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'DV1',
                'description' => 'Dévouteur de la station de vidange BB.',
                'zone_id' => 6,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VBB1',
                'description' => 'Vis de transfert de la station de vidange BB.',
                'zone_id' => 6,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'ECL6',
                'description' => 'Écluse servant pour le SO2 lors de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'SEP1 Séparateur/Aimant',
                'description' => 'Séparateur/Aimant de la station de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'FV4',
                'description' => 'Fond vibrant de la trémie de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VSO4',
                'description' => 'Trappe du souffleur de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'SO4',
                'description' => 'Souffleur de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'VG1',
                'description' => 'Trappe doseuse de trémie de remplissage BB.',
                'zone_id' => 7,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'CTA',
                'description' => 'CTA utilisée pour filtrer et refroidir l\'air de la salle blanche.',
                'zone_id' => 8,
                'incident_count' => 0,
                'maintenance_count' => 2,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Chaudières',
                'description' => 'Chaudières utilisé pour chauffer le conditionneur et le pré-conditionneur.',
                'zone_id' => 8,
                'incident_count' => 0,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Karcher',
                'description' => 'Karcher à eau chaude utilisé dans la salle blanche et Karcher utilisé dans la zone de lavage.',
                'zone_id' => 8,
                'incident_count' => 2,
                'maintenance_count' => 1,
                'cleaning_count' => 0,
                'part_count' => 1,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Armoires Électriques',
                'description' => 'Armoires Électriques de l\'usine.',
                'zone_id' => 8,
                'incident_count' => 2,
                'maintenance_count' => 0,
                'cleaning_count' => 0,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'user_id' => 1,
                'name' => 'Sol Salle Blanche',
                'description' => 'Sol de la salle blanche.',
                'zone_id' => 8,
                'incident_count' => 0,
                'maintenance_count' => 0,
                'cleaning_count' => 5,
                'part_count' => 0,
                'cleaning_test_ph_enabled' => 0,
                'created_at' => $now,
                'updated_at' => $now
            ],
        ];

        DB::table('materials')->insert($materials);
    }
}
