<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PartsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('parts')->delete();

        \DB::table('parts')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Ventouse 40mm',
                'description' => 'Ventouse 40mm utilisé dans le magasin pour la prise des sacs.',
                'user_id' => 1,
                'material_id' => 118,
                'reference' => 'DIA40VPA40NR',
                'supplier' => 'ORRECA',
                'price' => 10,
                'part_entry_total' => 37,
                'part_exit_total' => 5,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 18,
                'number_critical_enabled' => 1,
                'number_critical_minimum' => 9,
                'part_entry_count' => 1,
                'part_exit_count' => 1,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2022-06-23 22:02:34',
                'updated_at' => '2022-06-23 22:02:34',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Buse spéciale TR buse coudée Vario 0008',
                'description' => 'Buse réglable pour le Karcher HP en salle blanche.',
                'user_id' => 1,
                'material_id' => 135,
                'reference' => '4.113-006.0',
                'supplier' => 'FITECH',
                'price' => 165,
                'part_entry_total' => 0,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 0,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2022-06-23 22:02:34',
                'updated_at' => '2022-06-23 22:02:34',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'EDV EV068 C2F 68/68 D68 CLX205',
                'description' => 'Elément de vis en CLX205, position 6 à 12 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ927169',
                'supplier' => 'CLEXTRAL',
                'price' => 1013,
                'part_entry_total' => 4,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 2,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 09:08:29',
                'updated_at' => '2023-08-10 09:46:50',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'EDV EV068 C2F 51/51 D68 CLX205',
                'description' => 'Elément de vis en CLX205, position 6 à 12 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ927168',
                'supplier' => 'CLEXTRAL',
                'price' => 915,
                'part_entry_total' => 4,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 2,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 09:42:26',
                'updated_at' => '2023-08-10 09:46:43',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'EDV EV068 C2F 34/34 D68 CLX205',
                'description' => 'Elément de vis en CLX205, position 6 à 12 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ927167',
                'supplier' => 'CLEXTRAL',
                'price' => 825,
                'part_entry_total' => 4,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 09:44:09',
                'updated_at' => '2023-08-10 09:46:35',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'EDV EV068 IN00 EP17 DN68 CLX205 DROIT',
                'description' => 'Elément de vis en CLX205, position 6 à 12 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ927173',
                'supplier' => 'CLEXTRAL',
                'price' => 646,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 09:45:45',
                'updated_at' => '2023-08-10 09:45:45',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'EDV EV068 IN00 EP17 DN68 CLX205 GAUCHE',
                'description' => 'Elément de vis en CLX205, position 6 à 12 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ927174',
                'supplier' => 'CLEXTRAL',
                'price' => 646,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 09:49:14',
                'updated_at' => '2023-08-10 09:49:14',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'EDV EV068 C1F 34/34 D68 CLX205R',
                'description' => 'Elément de vis en CLX205R, position 13 à 31 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ932320',
                'supplier' => 'CLEXTRAL',
                'price' => 825,
                'part_entry_total' => 16,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 10:04:16',
                'updated_at' => '2023-08-10 10:04:16',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'EDV EV068 CF1C 34/34 D68 CLX205R 1S',
                'description' => 'Elément de vis en CLX205R, position 13 à 31 du profil de vis.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ZZ932319',
                'supplier' => 'CLEXTRAL',
                'price' => 1096,
                'part_entry_total' => 22,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 10:06:09',
                'updated_at' => '2023-08-10 10:06:09',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'S/E MDF FER EV068 DN68 CLX919R100',
                'description' => 'Module de fourreaux en CLX919R100',
                'user_id' => 1,
                'material_id' => 81,
                'reference' => 'WW105426',
                'supplier' => 'CLEXTRAL',
                'price' => 24746,
                'part_entry_total' => 0,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 0,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 10:17:16',
                'updated_at' => '2023-08-14 15:43:55',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Lame Rapportée Granulateur HC72 EP.05 Coup41',
                'description' => 'Lame utilisé dans les couteaux du granulateur.
Epaisseur : 0.5
Coup : 41',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'Z102250A',
                'supplier' => 'CLEXTRAL',
                'price' => 5,
                'part_entry_total' => 86,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 18,
                'number_critical_enabled' => 1,
                'number_critical_minimum' => 6,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 2,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 11:36:40',
                'updated_at' => '2023-08-10 16:29:47',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'S/E Palier de Guidage EV068 Reparé',
                'description' => 'Palier de guidage des vis réparé',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'W014796AREP',
                'supplier' => 'CLEXTRAL',
                'price' => 9115,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 11:40:27',
                'updated_at' => '2023-08-10 14:55:33',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Electrovanne DANFOSS D.IMP:1/4"BSPP 24VDC',
                'description' => 'Electrovanne utilisé pour la régularisation des températures des fourreaux.',
                'user_id' => 1,
                'material_id' => 81,
                'reference' => 'JAAL0285',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 0,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 0,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 11:43:22',
                'updated_at' => '2023-08-10 11:43:22',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Capteur de Température Jumo 90165F41',
                'description' => 'Sonde de température utilisé pour les fourreaux.
Type : J
Longueur : 200
Cable : 4M
D.IMP : 3',
                'user_id' => 1,
                'material_id' => 81,
                'reference' => 'SNAE0050',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 2,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 12:34:01',
                'updated_at' => '2023-08-10 12:34:01',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Ensemble Picot Droit Préconditionneur intensif 150L V3.0',
            'description' => 'Picot (palle) du préconditionneur.
1 Ensenble comprend :
1x Picot droit ZZ915673
1x Ecrou de Picot ZZ906484
1x Rondelle ANAB0021',
                'user_id' => 1,
                'material_id' => 75,
                'reference' => 'WW108912',
                'supplier' => 'CLEXTRAL',
                'price' => 343,
                'part_entry_total' => 2,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 13:03:39',
                'updated_at' => '2023-08-10 15:25:49',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Gâche Electrique ATLAS5+LAMP 24V AC/DC',
                'description' => 'Gâche Electrique du granulateur en 24V AC/DC.',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'SNAH0120',
                'supplier' => 'Bourgogne du Sud',
                'price' => 735,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 2,
                'edit_count' => 4,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-10 13:15:10',
                'updated_at' => '2023-08-10 14:41:02',
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Peigne Répartition Refroidisseur',
                'description' => 'Peigne de répartition du produit sur le tapis du refroidisseur.',
                'user_id' => 1,
                'material_id' => 95,
                'reference' => 'SERBPDR',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-10 14:48:17',
                'updated_at' => '2023-08-10 14:48:17',
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Grille T2 Trous Ronds 4mm',
                'description' => 'Grille du broyeur à coque en trous ronds 4mm.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-094-08-30',
                'supplier' => 'TOY',
                'price' => 69,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:07:40',
                'updated_at' => '2023-08-14 10:07:40',
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Support de Grille T2',
                'description' => 'Ensemble de support de grille T2 pour le broyeur à coque.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-028-16-10',
                'supplier' => 'TOY',
                'price' => 277,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:09:07',
                'updated_at' => '2023-08-14 10:09:07',
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Ventilateur 4 pâles 570mm',
                'description' => 'Ventilateur 4 pâles pour le broyeur à coque.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-028-13-20',
                'supplier' => 'TOY',
                'price' => 196,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:10:45',
                'updated_at' => '2023-08-14 10:10:45',
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Jeu de 4 Pâles de rotor T2',
                'description' => 'Un jeu de 4 pâles de rotor T2 pour le broyeur à coque.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-028-02-13A',
                'supplier' => 'TOY',
                'price' => 123,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:12:18',
                'updated_at' => '2023-08-14 10:12:18',
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Rotor T2',
                'description' => 'Rotor T2 du broyeur à coque',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-028-02-10',
                'supplier' => 'TOY',
                'price' => 372,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:31:53',
                'updated_at' => '2023-08-14 10:31:53',
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Jeu de 16 marteaux',
                'description' => 'Un jeu de 16 marteaux pour le broyeur à coque. Le jeu de 16 marteaux représente l\'intégralité des marteaux présent sur le rotor.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-990-33-75',
                'supplier' => 'TOY',
                'price' => 116,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:33:30',
                'updated_at' => '2023-08-14 10:33:30',
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Jeu de 16 entretoises',
                'description' => 'Un jeu de 16 entretoises utilisé pour la séparation entre les marteaux.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-990-33-71',
                'supplier' => 'TOY',
                'price' => 49,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:34:58',
                'updated_at' => '2023-08-14 10:34:58',
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Jeu de 4 axes',
                'description' => 'Un jeu de 4 axes qui servent de support pour les marteaux et entretoises du broyeur à coque.',
                'user_id' => 1,
                'material_id' => 12,
                'reference' => '0-990-33-69',
                'supplier' => 'TOY',
                'price' => 65,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:36:14',
                'updated_at' => '2023-08-14 10:36:14',
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Contre Lame LG 44.5 Entraxe vis LG 34.5 Granu HC72',
                'description' => 'Contre lame pour couteau granulateur :
Longueur : 44.5
Entraxe vis : 34.5',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'Z099503A',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 0,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 0,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:47:47',
                'updated_at' => '2023-08-14 10:47:47',
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Vis pour contre-lame couteau',
                'description' => 'Vis pour maintenir les contre-lames des couteaux du granulateur.',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'AAAL0020',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 8,
                'part_exit_total' => 0,
                'number_warning_enabled' => 1,
                'number_warning_minimum' => 4,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 10:55:54',
                'updated_at' => '2023-08-14 10:55:54',
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Vis pour maintien couteau',
                'description' => 'Vis servant à maintenir le couteau sur l\'arbre du granulateur.',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'AAAC0526',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 8,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-14 11:04:15',
                'updated_at' => '2023-08-14 11:04:40',
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Lame monobloc 4 coupes Coup.52 D140 EP15',
                'description' => 'Couteau monobloc 4 coupes.',
                'user_id' => 1,
                'material_id' => 84,
                'reference' => 'ZZ916914',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 11:09:40',
                'updated_at' => '2023-08-14 11:09:40',
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Pion 16x80 Mat:Z12C13',
                'description' => 'Pion pour le palier de guidage.',
                'user_id' => 1,
                'material_id' => 80,
                'reference' => 'ASAA0189',
                'supplier' => 'CLEXTRAL',
                'price' => 0,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 0,
                'is_edited' => 0,
                'edited_user_id' => NULL,
                'created_at' => '2023-08-14 11:49:59',
                'updated_at' => '2023-08-14 11:49:59',
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'S/E MDR FER EV068 DN68 CLX100',
                'description' => 'Module de fourreaux en CLX100',
                'user_id' => 1,
                'material_id' => 81,
                'reference' => 'W013449A',
                'supplier' => 'CLEXTRAL',
                'price' => 7005,
                'part_entry_total' => 1,
                'part_exit_total' => 0,
                'number_warning_enabled' => 0,
                'number_warning_minimum' => 0,
                'number_critical_enabled' => 0,
                'number_critical_minimum' => 0,
                'part_entry_count' => 1,
                'part_exit_count' => 0,
                'qrcode_flash_count' => 0,
                'edit_count' => 1,
                'is_edited' => 1,
                'edited_user_id' => 1,
                'created_at' => '2023-08-14 15:43:23',
                'updated_at' => '2023-08-14 15:43:46',
            ),
        ));


    }
}
